.JOB SOFTERM
.NOTIME
.NOLOG
/ ENTER 1 FOR MASTER PROGRAM, 2 FOR MONITOR PROGRAM \_
.ENTER 5
/
/ ENTER CRT NUMBER FOR THE COMMUNICATIONS LINE \_
.ENTER 6
/_
.SETC 2 = XSOFTRAN
.SKIP 1 IF #5 NE 1
.SETC 2 = XSOFTERM
.SETA 1=#S
.SETA UPSI=1
.FSPEC LOGPC#V ON #S 8=SIZE
.SKIP 1 IF #8 NE 0
.NEW LOGPC#V #S 'A' 1
.USE CRT#6 FOR SYS10
.USE LOGPC#V ON #S FOR SYSLST
.RUN PC.#2 ON #1
.SKIP 1 IF #C NE 50
/   PC.CENTURION IS NOT INITIALIZED
.END
S.CON