#!/bin/sh
#
# This ROM does setup and menu display. The menu is automatically generated by
# scanning every 2KB chunk from 0x8800 - 0xe800 looking for a table of offsets
# relative to that ROM start and the test name. When jumping to other ROMs, Z
# is set to the base address of that ROM so it can create a relocated jump table
# for indirect jumps to helper functions.

./scripts/disassm.py images/Diag_F1_Rev_1.0.BIN -rom -base 0x8000 -entry 0x0001 -force "0x81a1 0x81a3 0x826f 0x8282 0x8467 0x846d 0x8077 0x8000 0x808e 0x811b 0x8183 0x81dc 0x8203 0x8247 0x8284 0x82e3 0x837f 0x846f 0x859d 0x86b2 0x8728 0x8075" -subs '0x8623:args.index(0) + 1;;0x8634:0;;0x8520:0;;0x850e:0;;0x8500:0;;0x8568:0;;0x853a:0;;0x833f:0;;0x8137:0' $*

