.NOLOG
.JOB CED ABORT=CANCEL
.SETC 6='.'
/ ENTER INPUT LIBRARY OR "NEWLINE" FOR NONE
.ENTER 5
.SKIP 1 IF ? LE #5
.SETC 5='' 6=''
.FSPEC #5#6#0 ON #1 2=SIZE
.SKIP TO OK IF #2 GT 0
/ FILE '#5#6#0' NOT FOUND ON #1 CREATE(Y/N)?
.ENTER 2
.SKIP TO END IF Y NE #2
.NEW #5#6#0 ON #1 'A' 1T
=OK
.FSPEC @SCR#I ON #S 2=SIZE
.SKIP 1 IF #2 GT 0
.NEW @SCR#I #S 'A' 1T
.USE #5#6#0 ON #1 SYS000
.USE @SCR#I ON #S SYS001
.RUN XCED
=END
.USE CRT0 FOR SYSRDR
.END
.LOG
/ END CED
S.CON

