.NOLOG
.JOB CED
.FSPEC #0 ON #1 3=SIZE
.SKIP TO OK IF #3 GT 0
/ FILE '#0' NOT FOUND ON #1 CREATE(Y/N)?
.ENTER 3
.SKIP TO END IF Y NE #3
.NEW #0 ON #1 'A' 1
=OK
.FSPEC @SCR#I ON #S 3=SIZE
.SKIP 1 IF #3 GT 0
.NEW @SCR#I #S 'A' 1S
.USE #0 ON #1 FOR SYS000
.USE @SCR#I ON #S FOR SYS001
.SKIP 2 IF ? LE #2
.USE CRT#V FOR SYS002
.SKIP 1
.USE #2 FOR SYS002
.RUN XCED
=END
.END
.LOG
/ END CED
CON

