.JOB COPY ABORT=CANCEL
.SETC 6='.' 8='.'
/ ENTER INPUT LIBRARY OR "NEWLINE" FOR NONE
.ENTER 5
.SKIP 1 IF ? LE #5
.SETC 5='' 6=''
/ ENTER OUTPUT LIBRARY OR "NEWLINE" FOR NONE
.ENTER 7
.SKIP 1 IF ? LE #7
.SETC 7='' 8=''
.FSPEC #7#8#2 ON #3 9=SIZE
.SKIP 3 IF #9 GT 0
/ ENTER FILE TYPE
.ENTER 9
.NEW #7#8#2 ON #3 '#9' 1T
.USE #5#6#0 ON #1 FOR SYS0
.USE #7#8#2 ON #3 FOR SYS1
.RUN S.XCOPUT
.END
S.CON

