.NOLOG
.NOTIME
.JOB BASIC ABORT=CANCEL
.SETC 0='BASICPROG'
.FSPEC Z#0 ON #W 3=SIZE
.SKIP 1 IF #3 GT 0
.NEW Z#0 ON #W 'A' 1S
.USE Z#0 ON #W FOR SYS000
.RUN XBASICED
.USE Z#0 ON #W FOR SYS000
.FSPEC X#0 ON #W 3=SIZE
.SKIP 1 IF #3 GT 0
.NEW X#0 ON #W 'E' 1S NOCLR
.USE X#0 ON #W FOR SYS001
.USE DUMMY FOR SYS002
.RUN P.XBCOM
.SKIP 5 IF #C NE 0
/
/
.RUN X#0
.USE CRT#V FOR SYSRDR
.USE CRT#V FOR SYSLST
.END

